import React from 'react';
import Header from '@/components/Header';
import Carousel from '@/components/Carousel';
import { StickyScroll } from '@/components/StickyScrollReveal';

const contentData = [
  {
    title: 'Section 1',
    description: 'Content for Section 1 Content for Section 1Content for Section 1Content for Section 1Content for Section 1Content for Section 1Content for Section 1Content for Section 1Content for Section 1Content for Section 1Content for Section 1Content for Section 1Content for Section 1Content for Section 1Content for Section 1Content for Section 1Content for Section 1Content for Section 1Content for Section 1Content for Section 1Content for Section 1Content for Section 1Content for Section 1Content for Section 1Content for Section 1Content for Section 1Content for Section 1Content for Section 1Content for Section 1Content for Section 1Content for Section 1Content for Section 1Content for Section 1Content for Section 1Content for Section 1Content for Section 1Content for Section 1Content for Section 1Content for Section 1Content for Section 1',
    content: 'Content for Section 1 Content for Section 1Content for Section 1Content for Section 1Content for Section 1Content for Section 1Content for Section 1Content for Section 1Content for Section 1Content for Section 1Content for Section 1Content for Section 1Content for Section 1Content for Section 1Content for Section 1Content for Section 1Content for Section 1Content for Section 1Content for Section 1Content for Section 1Content for Section 1Content for Section 1Content for Section 1Content for Section 1Content for Section 1Content for Section 1Content for Section 1Content for Section 1Content for Section 1Content for Section 1Content for Section 1Content for Section 1Content for Section 1Content for Section 1Content for Section 1Content for Section 1Content for Section 1Content for Section 1Content for Section 1Content for Section 1'
  },
  {
    title: 'Section 2',
    description: 'Content for Section 1 Content for Section 1Content for Section 1Content for Section 1Content for Section 1Content for Section 1Content for Section 1Content for Section 1Content for Section 1Content for Section 1Content for Section 1Content for Section 1Content for Section 1Content for Section 1Content for Section 1Content for Section 1Content for Section 1Content for Section 1Content for Section 1Content for Section 1Content for Section 1Content for Section 1Content for Section 1Content for Section 1Content for Section 1Content for Section 1Content for Section 1Content for Section 1Content for Section 1Content for Section 1Content for Section 1Content for Section 1Content for Section 1Content for Section 1Content for Section 1Content for Section 1Content for Section 1Content for Section 1Content for Section 1Content for Section 1',
    content: 'Content for Section 1 Content for Section 1Content for Section 1Content for Section 1Content for Section 1Content for Section 1Content for Section 1Content for Section 1Content for Section 1Content for Section 1Content for Section 1Content for Section 1Content for Section 1Content for Section 1Content for Section 1Content for Section 1Content for Section 1Content for Section 1Content for Section 1Content for Section 1Content for Section 1Content for Section 1Content for Section 1Content for Section 1Content for Section 1Content for Section 1Content for Section 1Content for Section 1Content for Section 1Content for Section 1Content for Section 1Content for Section 1Content for Section 1Content for Section 1Content for Section 1Content for Section 1Content for Section 1Content for Section 1Content for Section 1Content for Section 1'
  },
  {
    title: 'Section 3',
    description: 'Content for Section 1 Content for Section 1Content for Section 1Content for Section 1Content for Section 1Content for Section 1Content for Section 1Content for Section 1Content for Section 1Content for Section 1Content for Section 1Content for Section 1Content for Section 1Content for Section 1Content for Section 1Content for Section 1Content for Section 1Content for Section 1Content for Section 1Content for Section 1Content for Section 1Content for Section 1Content for Section 1Content for Section 1Content for Section 1Content for Section 1Content for Section 1Content for Section 1Content for Section 1Content for Section 1Content for Section 1Content for Section 1Content for Section 1Content for Section 1Content for Section 1Content for Section 1Content for Section 1Content for Section 1Content for Section 1Content for Section 1',
    content: 'Content for Section 1 Content for Section 1Content for Section 1Content for Section 1Content for Section 1Content for Section 1Content for Section 1Content for Section 1Content for Section 1Content for Section 1Content for Section 1Content for Section 1Content for Section 1Content for Section 1Content for Section 1Content for Section 1Content for Section 1Content for Section 1Content for Section 1Content for Section 1Content for Section 1Content for Section 1Content for Section 1Content for Section 1Content for Section 1Content for Section 1Content for Section 1Content for Section 1Content for Section 1Content for Section 1Content for Section 1Content for Section 1Content for Section 1Content for Section 1Content for Section 1Content for Section 1Content for Section 1Content for Section 1Content for Section 1Content for Section 1'
  },
  {
    title: 'Section 4',
    description: 'Content for Section 1 Content for Section 1Content for Section 1Content for Section 1Content for Section 1Content for Section 1Content for Section 1Content for Section 1Content for Section 1Content for Section 1Content for Section 1Content for Section 1Content for Section 1Content for Section 1Content for Section 1Content for Section 1Content for Section 1Content for Section 1Content for Section 1Content for Section 1Content for Section 1Content for Section 1Content for Section 1Content for Section 1Content for Section 1Content for Section 1Content for Section 1Content for Section 1Content for Section 1Content for Section 1Content for Section 1Content for Section 1Content for Section 1Content for Section 1Content for Section 1Content for Section 1Content for Section 1Content for Section 1Content for Section 1Content for Section 1',
    content: 'Content for Section 1 Content for Section 1Content for Section 1Content for Section 1Content for Section 1Content for Section 1Content for Section 1Content for Section 1Content for Section 1Content for Section 1Content for Section 1Content for Section 1Content for Section 1Content for Section 1Content for Section 1Content for Section 1Content for Section 1Content for Section 1Content for Section 1Content for Section 1Content for Section 1Content for Section 1Content for Section 1Content for Section 1Content for Section 1Content for Section 1Content for Section 1Content for Section 1Content for Section 1Content for Section 1Content for Section 1Content for Section 1Content for Section 1Content for Section 1Content for Section 1Content for Section 1Content for Section 1Content for Section 1Content for Section 1Content for Section 1'
  },
  {
    title: 'Section 5',
    description: 'Content for Section 1 Content for Section 1Content for Section 1Content for Section 1Content for Section 1Content for Section 1Content for Section 1Content for Section 1Content for Section 1Content for Section 1Content for Section 1Content for Section 1Content for Section 1Content for Section 1Content for Section 1Content for Section 1Content for Section 1Content for Section 1Content for Section 1Content for Section 1Content for Section 1Content for Section 1Content for Section 1Content for Section 1Content for Section 1Content for Section 1Content for Section 1Content for Section 1Content for Section 1Content for Section 1Content for Section 1Content for Section 1Content for Section 1Content for Section 1Content for Section 1Content for Section 1Content for Section 1Content for Section 1Content for Section 1Content for Section 1',
    content: 'Content for Section 1 Content for Section 1Content for Section 1Content for Section 1Content for Section 1Content for Section 1Content for Section 1Content for Section 1Content for Section 1Content for Section 1Content for Section 1Content for Section 1Content for Section 1Content for Section 1Content for Section 1Content for Section 1Content for Section 1Content for Section 1Content for Section 1Content for Section 1Content for Section 1Content for Section 1Content for Section 1Content for Section 1Content for Section 1Content for Section 1Content for Section 1Content for Section 1Content for Section 1Content for Section 1Content for Section 1Content for Section 1Content for Section 1Content for Section 1Content for Section 1Content for Section 1Content for Section 1Content for Section 1Content for Section 1Content for Section 1'
  },

  // Add more sections as needed
];

const HomePage: React.FC = () => {
  return (
    <div>
      <Header />
      <Carousel/>
      <StickyScroll content={contentData} />
      {/* Rest of the landing page content */}
    </div>
  );
};

export default HomePage;